### ISSUE TITLE
Issue with output

### ISSUE THREAD

**Issue by overthink** [jjhartmann/solid-lamp#1]
Hi Jeremy,

I was trying to evaluate your solution but there is a problem with the output format.  My scoring script expects listings in your results file to be exactly as they appear in listings.txt.  I think in your case the list titles are lower-cased in the output, which is causing problems for me.

An example valid line in the output file should look like:

```
{"listings": [{"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Red)"}, {"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio Exilim EX-FC150 10.1MP High Speed Digital Camera with 5x Optical Zoom, CMOS Shift Image Stabilization & 2.7-inch LCD (Red)"}, {"currency": "USD", "price": "249.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Black)"}], "product_name": "Casio_Exilim_EX-FC150"}
```

If you are able to fix this up I'd be happy to take another look at your submission.

Thanks!

Mark (from sortable.com)

**Comment by jjhartmann** [comment]
Hi Mark,

Thanks for letting me know about the issue. I pushed some changes to this repo that should address the "title" string problem that you mentioned. 

Everything should be fixed and up to date as of tonight. 

Thanks!
++J

**Comment by overthink** [comment]
Thanks Jeremy.  Looks good now!

Mark
